apiVersion: v1
kind: Service
metadata:
  name: hellolearneruser
spec:
  selector:
    app: hellolearneruser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
