apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmos-transfer
  labels:
    app: cosmos-transfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmos-transfer
  template:
    metadata:
      labels:
        app: cosmos-transfer
    spec:
      containers:
      - name: cosmos-transfer
        image: acrsurenlearning.azurecr.io/cosmos-transfer:latest
        env:
        - name: COSMOS_DB_ENDPOINT
          value: "https://raglearning1.documents.azure.com:443/"
        - name: COSMOS_DB_KEY
          value: "dummy"
        - name: COSMOS_DB_DATABASE
          value: "n8n"
        ports:
        - containerPort: 8080
