apiVersion: v1
kind: Service
metadata:
  name: jsontransformation
spec:
  selector:
    app: jsontransformation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
