apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmos-transfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmos-transfer
  template:
    metadata:
      labels:
        app: cosmos-transfer
    spec:
      containers:
        - name: cosmos-transfer
          image: acrsurenlearning.azurecr.io/cosmos-transfer:latest
          ports:
            - containerPort: 8080
          env:
            - name: AZURE_COSMOS_KEY
              value: "dummy"
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
