apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmos-data-transform
  labels:
    app: datatodatatransform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datatodatatransform
  template:
    metadata:
      labels:
        app: datatodatatransform
    spec:
      containers:
        - name: datatodatatransform
          image: acrsurenlearning.azurecr.io/cosmos-transfer:latest
          env:
            - name: COSMOS_KEY
              value: "dummy"
          ports:
            - containerPort: 8080
