apiVersion: v1
kind: Service
metadata:
  name: cosmos-data-transform-service
spec:
  type: ClusterIP
  selector:
    app: datatodatatransform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
