apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsontestingtaransform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsontestingtaransform
  template:
    metadata:
      labels:
        app: jsontestingtaransform
    spec:
      containers:
      - name: jsontestingtaransform
        image: jsontestingtaransform:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jsontestingtaransform
spec:
  selector:
    app: jsontestingtaransform
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
