apiVersion: v1
kind: Service
metadata:
  name: hellouseroptum
spec:
  selector:
    app: hellouseroptum
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
