apiVersion: apps/v1
kind: Deployment
metadata:
  name: 23000testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 23000testing
  template:
    metadata:
      labels:
        app: 23000testing
    spec:
      containers:
        - name: 23000testing
          image: acrsurenlearning.azurecr.io/23000testing:latest
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: 23000testing-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: 23000testing