apiVersion: apps/v1
kind: Deployment
metadata:
  name: 6000testing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 6000testing
  template:
    metadata:
      labels:
        app: 6000testing
    spec:
      containers:
      - name: 6000testing
        image: acrsurenlearning.azurecr.io/6000testing:latest
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: ""
