apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmos-transfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmos-transfer
  template:
    metadata:
      labels:
        app: cosmos-transfer
    spec:
      containers:
        - name: cosmos-transfer
          image: acrsurenlearning.azurecr.io/cosmos-transfer:latest
          ports:
            - containerPort: 8080
          env:
            - name: COSMOS_DB_URI
              value: "https://raglearning1.documents.azure.com:443/"
            - name: COSMOS_DB_KEY
              value: "dummy"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
