apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmos-transfer
  labels:
    app: cosmos-transfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmos-transfer
  template:
    metadata:
      labels:
        app: cosmos-transfer
    spec:
      containers:
        - name: cosmos-transfer
          image: acrsurenlearning.azurecr.io/cosmos-transfer:latest
          ports:
            - containerPort: 8080
          env:
            - name: COSMOS_KEY
              valueFrom:
                secretKeyRef:
                  name: cosmos-key-secret
                  key: cosmos-key
---
apiVersion: v1
kind: Secret
metadata:
  name: cosmos-key-secret
stringData:
  cosmos-key: dummy
