apiVersion: v1
kind: Service
metadata:
  name: hello-user-service
spec:
  selector:
    app: hello-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
