apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-suren
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld-suren
  template:
    metadata:
      labels:
        app: helloworld-suren
    spec:
      containers:
      - name: helloworld-suren
        image: helloworld-suren:latest
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-suren-service
spec:
  selector:
    app: helloworld-suren
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
