apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8nhello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8nhello
  template:
    metadata:
      labels:
        app: n8nhello
    spec:
      containers:
        - name: n8nhello
          image: n8nhello:latest
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: n8nhello-service
spec:
  selector:
    app: n8nhello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
