apiVersion: apps/v1
kind: Deployment
metadata:
  name: 10000testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 10000testing
  template:
    metadata:
      labels:
        app: 10000testing
    spec:
      containers:
        - name: 10000testing
          image: acrsurenlearning.azurecr.io/10000testing:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: default
---
apiVersion: v1
kind: Service
metadata:
  name: 10000testing-service
spec:
  type: LoadBalancer
  selector:
    app: 10000testing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
