apiVersion: v1
kind: Service
metadata:
  name: testing123-service
  namespace: ${AKS_NAMESPACE}
spec:
  selector:
    app: testing123
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
