apiVersion: v1
kind: Service
metadata:
  name: datatojsontransformation
spec:
  selector:
    app: datatojsontransformation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
