apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-suren-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-suren
  template:
    metadata:
      labels:
        app: hello-suren
    spec:
      containers:
      - name: hello-suren
        image: hello-suren:latest
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: hello-suren-service
spec:
  type: ClusterIP
  selector:
    app: hello-suren
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
