apiVersion: apps/v1
kind: Deployment
metadata:
  name: 3000testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 3000testing
  template:
    metadata:
      labels:
        app: 3000testing
    spec:
      containers:
      - name: 3000testing
        image: acrsurenlearning.azurecr.io/3000testing:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "default"
---
apiVersion: v1
kind: Service
metadata:
  name: 3000testing-svc
spec:
  type: LoadBalancer
  selector:
    app: 3000testing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
