apiVersion: apps/v1
kind: Deployment
metadata:
  name: fivetesting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fivetesting
  template:
    metadata:
      labels:
        app: fivetesting
    spec:
      containers:
      - name: fivetesting
        image: acrsurenlearning.azurecr.io/fivetesting:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "default"
---
apiVersion: v1
kind: Service
metadata:
  name: fivetesting-service
spec:
  type: LoadBalancer
  selector:
    app: fivetesting
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
