apiVersion: v1
kind: Service
metadata:
  name: datatransformation
spec:
  selector:
    app: datatransformation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
