apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2000testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 2000testing
  template:
    metadata:
      labels:
        app: 2000testing
    spec:
      containers:
        - name: 2000testing
          image: 2000testing:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: 2000testing-service
spec:
  type: LoadBalancer
  selector:
    app: 2000testing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
