apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-hello-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-hello
  template:
    metadata:
      labels:
        app: springboot-hello
    spec:
      containers:
      - name: springboot-hello
        image: acrsurenlearning.azurecr.io/7000testing:latest
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: ""
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-hello-service
spec:
  selector:
    app: springboot-hello
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer