apiVersion: apps/v1
kind: Deployment
metadata:
  name: 50000testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 50000testing
  template:
    metadata:
      labels:
        app: 50000testing
    spec:
      containers:
        - name: 50000testing
          image: 50000testing:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: 50000testing
spec:
  selector:
    app: 50000testing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
