apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-6000
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-6000
  template:
    metadata:
      labels:
        app: app-6000
    spec:
      containers:
      - name: app-6000
        image: app-6000:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-6000
spec:
  selector:
    app: app-6000
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
