apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworldsuren-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworldsuren
  template:
    metadata:
      labels:
        app: helloworldsuren
    spec:
      containers:
        - name: helloworldsuren
          image: helloworldsuren:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: helloworldsuren-service
spec:
  type: ClusterIP
  selector:
    app: helloworldsuren
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
