apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmos-transfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmos-transfer
  template:
    metadata:
      labels:
        app: cosmos-transfer
    spec:
      containers:
      - name: cosmos-transfer
        image: cosmos-transfer:latest
        ports:
        - containerPort: 8080
        env:
        - name: COSMOS_URI
          valueFrom:
            secretKeyRef:
              name: cosmos-secrets
              key: uri
        - name: COSMOS_KEY
          valueFrom:
            secretKeyRef:
              name: cosmos-secrets
              key: key
        - name: COSMOS_DB
          valueFrom:
            secretKeyRef:
              name: cosmos-secrets
              key: database
