apiVersion: apps/v1
kind: Deployment
metadata:
  name: 30000testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 30000testing
  template:
    metadata:
      labels:
        app: 30000testing
    spec:
      containers:
      - name: 30000testing
        image: 30000testing:latest
        ports:
        - containerPort: 8080
