apiVersion: v1
kind: Service
metadata:
  name: cosmos-transfer
spec:
  type: ClusterIP
  selector:
    app: cosmos-transfer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
