apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosmos-transfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosmos-transfer
  template:
    metadata:
      labels:
        app: cosmos-transfer
    spec:
      containers:
        - name: cosmos-transfer
          image: acrsurenlearning.azurecr.io/cosmos-transfer:latest
          env:
            - name: COSMOS_URI
              value: "https://raglearning1.documents.azure.com:443/"
            - name: COSMOS_KEY
              value: "dummy"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: cosmos-transfer
spec:
  selector:
    app: cosmos-transfer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
