apiVersion: v1
kind: Service
metadata:
  name: datatojsontransformationoptum
spec:
  selector:
    app: datatojsontransformationoptum
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
